project:
  type: website
  output-dir: docs

engine: julia

website:
  title: "SimilaritySearch"
  navbar:
    left:
      - href: index.qmd
        text: "Home"      
      - href: tutorials/index.qmd
        text: "Tutorials"
      - href: demos/index.qmd
        text: "Examples and demos"
      - href: about.qmd
        text: "About"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



