project:
  type: website
  output-dir: docs

engine: julia

execute:
  freeze: auto

website:
  title: "SimilaritySearch"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Tutorial"
        url: "https://sadit.github.io/SimilaritySearch.jl/dev/tutorial/"
      - href: demos/index.qmd
        text: "Demos"
      - href: about.qmd
        text: "About"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
