---
title: "Using the `SimilaritySearch` package"
engine: julia
lang: en-US

---

by: Eric S. Téllez

```{julia}
#| output: false
using SimilaritySearch, Markdown
using PlotlyLight
```

```{julia}
#| output: false
#| echo: false
PlotlyLight.settings.use_iframe = true # needed by quarto
PlotlyLight.settings.iframe_style = "display:block; border:none; min-height:350px; min-width:350px; width:6in; height:6in;" 

```


This is a small tutorial showing a minimum example for working with `SimilaritySearch` it accepts several options that are let to defaults. While this should be enough for many purposes, you are invited to see the rest of the tutorials to take advantage of other features.

MatrixDatabase is a required wrapper that tells `SimilaritySearch` how to access underlying objects since it can support different kinds of objects. In this setup, each column is an object and will be accessed through views using the MatrixDatabase. Since the backend doesn't support appends or pushes, the index can be seen as an static index.

```{julia}
#| output: false
function synthetic_benchmark(n, m, dim)
    db = MatrixDatabase(randn(Float32, dim, n))  # <1>
    queries = MatrixDatabase(randn(Float32, dim, m))
    dist = Dist.SqL2()  # <2>
    (; db, queries, dist) # <3>
end
```

it can use any distance function described in `SimilaritySearch` and `Distances.jl`, and in fact any `SemiMetric` as described in the later package. The index construction is made as follows

```{julia}
#| output: false
B = synthetic_benchmark(3000, 50, 2)
G = SearchGraph(; B.dist, B.db)
ctx = SearchGraphContext()
index!(G, ctx)
```
<!--
- callbacks = SearchGraphCallbacks(hyperparameters=OptimizeParameters(MinRecall(0.9)))
- optimize!(G; callbacks)-->

this will display a lot of information in the console, since as construction advances the hyperparameters of the index are adjusted. The default optimization try to get a recall of `0.9` which is a typical tradeoff between quality and speed. Once the index is created, the index can solve nearest neighbor queries

```{julia}
#| output: false
k = 16
knns = searchbatch(G, ctx, B.queries, k) #<1>
```
1. The `searchbatch` functions takes a set of queries and solve them using the given index. `knns` is a matrix with identifiers and their corresponding distances packed into a special structure `IdDist`.
 
## Visualizing what we just did

Now we wil visualize points with plotlyjs (through `PlotlyLight`)

```{julia}
#| fig-width: 6
#| fig-height: 6
#| fig-cap: "Visualizing the datasets, queries and its associated knns points"

data = Config[]

# plotting database
push!(data, Config(
    x = B.db.matrix[1, :],
    y = B.db.matrix[2, :],
    mode = "markers",
    marker = (color = "cyan", opacity = 0.3, size = 2, line = (width = 0,)),
    name = "Database",
    showlegend = false
))

# plotting search results (i-th column is associated with i-th query)
for (qID, c) in enumerate(eachcol(knns))
    indices = sort!(collect(IdView(c)))
    R = B.db.matrix[:, indices]
    
    push!(data, Config(
        x = R[1, :],
        y = R[2, :],
        mode = "markers",
        marker = (symbol = "diamond", opacity = 0.3, size = 6, line = (width = 0,)),
        name = "neighbors of qID $qID",
        showlegend = false
    ))
end

# plotting queries
push!(data, Config(
    x = B.queries.matrix[1, :],
    y = B.queries.matrix[2, :],
    mode = "markers",
    marker = (symbol = "star", color = "black", opacity = 0.5, size = 10, line = (width = 0,)),
    name = "Queries",
    showlegend = false
))

# Configuring the layout
layout = Config(
    width = 600,
    height = 600,
    xaxis = (
        range = [-3.6, 3.6],
    ),
    yaxis = (
        range = [-3.6, 3.6],
    ),

    #margin = (t = 20, b = 20, l = 20, r = 20),
    hovermode = "closest"
)

Plot(data, layout)

```

## Environment and dependencies
```{julia}
#| echo: false
versioninfo()

using Pkg
Pkg.status() 
```
