---
title: "Visualizing Twitter Messages with Emojis"
engine: julia
lang: en-US
---

This example creates a vector space model for classify emojis in Twitter messages, then process and create vectors from messages and project them using a UMAP model. The projection uses the SimilaritySearch `allknn` operation.

```{julia}
#| output: false
using SimilaritySearch, SimSearchManifoldLearning, TextSearch, CodecZlib, JSON, DataFrames, PlotlyLight, StatsBase
using Downloads: download

```

```{julia}
#| output: false
#| echo: false
PlotlyLight.settings.use_iframe = true # needed by quarto
PlotlyLight.settings.iframe_style = "display:block; border:none; min-height:350px; min-width:350px; width:6in; height:6in;"
```

downloading the dataset, parsing and vectorizing functions
```{julia}
#| output: true

mkpath("tmp")
dbfile = "tmp/emo50k.json.gz"
baseurl = "https://github.com/sadit/TextClassificationTutorial/raw/refs/heads/main/data/emo50k.json.gz"
!isfile(dbfile) && download(baseurl, dbfile)
```

Now, we load the dataset
```{julia}
#| output: true

D = DataFrame(open(GzipDecompressorStream, dbfile) do f
    JSON.parse.(eachline(f))
end)

collect(countmap(D.klass))
```

```{julia}

D = filter(D) do r
    r.klass in ("😭", "🤣", "😍", "😤")
end

collect(countmap(D.klass))
#H = sort!(collect(countmap(D.klass)), by=first)
#bar(first.(H), last.(H))
```

Functions create to encode texto into bag-of-word vectors
```{julia}
#| output: false

textconfig = TextConfig(
    group_usr=true,
    group_url=true,
    del_diac=true,
    lc=true,
    group_num=true,
    nlist=[1],
    qlist=[3])

# corpus here can be a sample to avoid double parsing
voc = Vocabulary(textconfig, D.text) 
# model = VectorModel(IdfWeighting(), TfWeighting(), voc)
model = VectorModel(EntropyWeighting(), BinaryLocalWeighting(), voc, D.text, D.klass; smooth=1.0)
#model = VectorModel(IdfWeighting(), TfWeighting(), voc)
model = filter_tokens(model) do t
    t.weight >= 0.075
end
vectors = VectorDatabase(vectorize_corpus(model, D.text))
```

## UMAP projections
UMAP projection can take a while, even on multithreading systems. Note that we are creating 2d and 3d projections.

```{julia}
#| output: false
e2, e3 = let min_dist=0.5f0, # <1>
             k=16,
             n_epochs=75,
             neg_sample_rate=3,
             tol=1e-3,
             layout=SpectralLayout(),
             indexsize=768,
             dist=Dist.NormCosine()

    index = ExhaustiveSearch(; db=rand(vectors, indexsize), dist) # <2>
    @time U2 = fit(UMAP, index; k, neg_sample_rate, layout, n_epochs, tol, min_dist) # <3>
    @time U3 = fit(U2, 3; neg_sample_rate, n_epochs, tol)  # <4>
    @time e2 = clamp.(predict(U2, vectors), -10f0, 10f0) # <5>
    @time e3 = clamp.(predict(U3, vectors), -10f0, 10f0) # <6>
    e2, e3
end

```
1. The UMAP algorithm has a lot of hyperparameters; `min_dist` controls the distance between projected points, `k` is the number of neighbors to be used in the underlying $k$nn graph, `n_epochs` the number of epochs used to optimize the projection, `neg_sample_rate` means for the number of negative examples used in the optimization process, `tol` the tolerance to converge, `layout` 

## Visualizations

Plots
```{julia}

function normcolors!(V)
    min_, max_ = extrema(V)
    range = max_ - min_
    if range > 0
        V .= (V .- min_) ./ range
    end
    V .= clamp.(V, 0, 1)
end

normcolors!(@view e3[1, :])
normcolors!(@view e3[2, :])
normcolors!(@view e3[3, :])

colors = [
    "rgba($(round(Int, c[1]*255)), $(round(Int, c[2]*255)), $(round(Int, c[3]*255)), 0.3)" 
    for c in eachcol(e3)
]

data = [Config(;
    x = view(e2, 1, :),
    y = view(e2, 2, :),
    mode = "markers",
    marker = (
        color = colors, 
        size = 4, 
        line = (width = 0,)
    ),
    hovertext = D.klass,
    type = "scattergl" 
)]

layout = Config(
    width = 600,
    height = 600,
    xaxis = (visible = false, showgrid = false, zeroline = false),
    yaxis = (visible = false, showgrid = false, zeroline = false),
    hovermode = "closest",
    plot_bgcolor = "white"
)

Plot(data, layout)

```

## Environment and dependencies
```{julia}
#| echo: false
versioninfo()

using Pkg
Pkg.status() 
```
