---
title: "Using with `ManifoldLearning`"
engine: julia
lang: en-US
---

by: Eric S. Téllez


This demonstration is about using `SimilaritySearch` and `ManifoldLearning` methods through `SimSearchManifoldLearning`.



```{julia}
#| output: false
using SimilaritySearch, SimSearchManifoldLearning, ManifoldLearning, Primes, PlotlyLight, StatsBase, LinearAlgebra, Markdown, Random
```

```{julia}
#| output: false
#| echo: false
PlotlyLight.settings.use_iframe = true # needed by quarto
PlotlyLight.settings.iframe_style = "display:block; border:none; min-height:350px; min-width:350px; width:6in; height:6in;"
```

## SCurve example

```{julia}

X, L = ManifoldLearning.scurve(segments=5)

data = [Config(
    x = X[1, :],
    y = X[2, :],
    z = X[3, :],
    type = "scatter3d",
    mode = "markers",
    marker = (
        color = L,
        colorscale = "Viridis", # "Default", "Portland", "Jet", etc.
        size = 3,
        opacity = 0.5,
        line = (width = 0,)
    )
)]

layout = Config(
    width = 800,
    height = 800,
    scene = Config(
        xaxis = (title = "X",),
        yaxis = (title = "Y",),
        zaxis = (title = "Z",),
        aspectmode = "cube" # Mantiene las proporciones iguales en los 3 ejes
    ),
)

Plot(data, layout)
```

`SimilaritySearch` support exact and approximate algorithms to solve `k` nearest neighbors. Also, it supports different metrics. For instance, let see how the selection of the distance function modifies the projection.

### Manhattan distance ($L_1$)
```{julia}
let	Y = predict(fit(Isomap, X, nntype=ApproxManhattan))
	data = [Config(
    x = Y[1, :],
    y = Y[2, :],
    type = "scatter",
    mode = "markers",
    marker = (
        color = L,
        colorscale = "Viridis", # "Default", "Portland", "Jet", etc.
        size = 3,
        opacity = 0.5,
        line = (width = 0,)
    )
)]

	Plot(data)
end
```

### Euclidean distance ($L_2$)

```{julia}
let
  E = predict(fit(Isomap, X, nntype=ApproxEuclidean))
	data = [Config(
    x = E[1, :],
    y = E[2, :],
    type = "scatter",
    mode = "markers",
    marker = (
        color = L,
        colorscale = "Viridis", # "Default", "Portland", "Jet", etc.
        size = 3,
        opacity = 0.5,
        line = (width = 0,)
    )
  )]

	Plot(data)
end
```

### Chebyshev distance ($L_\infty$)
```{julia}
let
	Ch = predict(fit(Isomap, X, nntype=ApproxChebyshev))
	data = [Config(
    x = Ch[1, :],
    y = Ch[2, :],
    type = "scatter",
    mode = "markers",
    marker = (
        color = L,
        colorscale = "Viridis", # "Default", "Portland", "Jet", etc.
        size = 3,
        opacity = 0.5,
        line = (width = 0,)
    )
  )]

end
```


## Visualizing prime gaps

The difference between contiguous prime numbers is called a [Prime gap](https://en.wikipedia.org/wiki/Prime_gap). We use this series of values as a time series example due to its interesting behavior and since it can be computed without downloading more than the necessary packages.

This example shows how to generate the dataset and index it. We will use the `ManifoldLearning` for generating the 2d visualization. 

### Generation of the dataset

The time series is represented with windows of size `w`, we also take `log` of gaps to reduce variance in gap values. We create a matrix to avoid redefinition of the knn interface for `ManifoldLearning`.

```{julia}
#| output: false
function create_database_primes_diff(n, w)
	T = log2.(diff(primes(n)))
	M = Matrix{Float32}(undef, w, length(T) - w)
	@info size(M)
	for i in 1:size(M, 2)
		M[:, i] .= view(T, i:(i+w-1))
	end

	M
end

x, y = let
    P = create_database_primes_diff(3 * 10^4, 5)
    # or LLE
    primesgap = fit(Isomap, P; k=16, maxoutdim=2, nntype=ApproxEuclidean)
    
	p = predict(primesgap)
	p[1, :], p[2, :]
end
```

A 2D histogram
```{julia}
data = [Config(;
    x = x,
    y = y,
    type = "histogram2d",
    colorscale = "Viridis",   
    nbinsx = 50,
    nbinsy = 50, 
    colorbar = (title = "freq",)
)]

layout = Config(
    title = "Isomap proj. 2D of prime gaps",
    width = 600,
    height = 600,
    xaxis = (title = "X",),
    yaxis = (title = "Y",),
)

Plot(data, layout)
```


## Environment and dependencies
```{julia}
#| echo: false
versioninfo()

using Pkg
Pkg.status() 
```
